from datetime import datetime

def send_sos_email(send_email, user, latitude, longitude):
    if not user.emergency_contact_email:
        print("❌ No emergency contact email found")
        return

    subject = "🚨 URGENT SOS ALERT – Immediate Assistance Required"

    body = f"""
🚨 EMERGENCY SOS ALERT 🚨

This is an automated emergency alert generated by the TravelBuddy Safety System.

⚠️ A registered traveler has pressed the SOS button and may be in danger.

--------------------------------------------------
TRAVELER DETAILS
--------------------------------------------------
Name              : {user.name}
Registered Email  : {user.email}
Contact Number    : {user.phone_number}

--------------------------------------------------
LAST KNOWN LOCATION
--------------------------------------------------
Latitude  : {latitude}
Longitude : {longitude}

Google Maps Link:
https://www.google.com/maps?q={latitude},{longitude}

--------------------------------------------------
TIME OF ALERT
--------------------------------------------------
{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

--------------------------------------------------
IMPORTANT ACTION REQUIRED
--------------------------------------------------
• Please contact the traveler immediately.
• If unreachable, inform local emergency services.
• Share this location with responders.

⚠️ DO NOT IGNORE THIS MESSAGE.

— TravelBuddy Safety Team
"""

    send_email(subject, [user.emergency_contact_email], body)
    print("✅ SOS EMAIL SENT")


def send_trip_created_email(send_email, user, trip):
    subject = "✅ Trip Confirmed – Your TravelBuddy Journey Begins!"

    body = f"""
Hello {user.name},

Your trip has been successfully registered in the TravelBuddy system.

--------------------------------------------------
TRIP DETAILS
--------------------------------------------------
Trip Title   : {trip.title}
Destination  : {trip.destination}
Start Date   : {trip.start_date}
End Date     : {trip.end_date}
Budget       : ₹{trip.budget}

--------------------------------------------------
SAFETY STATUS
--------------------------------------------------
✔ SOS Emergency Button Enabled
✔ Emergency Contact Linked
✔ Real-time Tracking Available

We wish you a safe and memorable journey.

— TravelBuddy Team
"""

    send_email(subject, [user.email], body)
    print("✅ Trip Created Email Sent")


def send_trip_updated_email(send_email, user, trip):
    subject = "✏️ Trip Updated – Please Review Changes"

    body = f"""
Hello {user.name},

Your trip details have been successfully updated.

--------------------------------------------------
UPDATED TRIP DETAILS
--------------------------------------------------
Trip Title   : {trip.title}
Destination  : {trip.destination}
Start Date   : {trip.start_date}
End Date     : {trip.end_date}
Budget       : ₹{trip.budget}

Please review the changes in your dashboard.

— TravelBuddy Team
"""

    send_email(subject, [user.email], body)
    print("✅ Trip Updated Email Sent")


def send_trip_deleted_email(send_email, user, trip):
    subject = "❌ Trip Deleted – Confirmation Notice"

    body = f"""
Hello {user.name},

This email confirms that the following trip has been deleted:

--------------------------------------------------
TRIP DETAILS
--------------------------------------------------
Trip Title  : {trip.title}
Destination : {trip.destination}

If this was not intentional, please contact support immediately.

— TravelBuddy Team
"""

    send_email(subject, [user.email], body)
    print("✅ Trip Deleted Email Sent")


def send_trip_start_reminder(send_email, user, trip):
    subject = "⏰ Trip Reminder – Your Journey Starts Tomorrow!"

    body = f"""
Hello {user.name},

This is a reminder that your upcoming trip begins soon.

--------------------------------------------------
UPCOMING TRIP
--------------------------------------------------
Destination : {trip.destination}
Start Date  : {trip.start_date}
End Date    : {trip.end_date}

--------------------------------------------------
SAFETY REMINDERS
--------------------------------------------------
✔ Keep your phone charged
✔ Enable GPS & Internet
✔ SOS button is active
✔ Emergency contact is linked

Have a safe journey!

— TravelBuddy Safety Team
"""

    send_email(subject, [user.email], body)
    print("✅ Trip Reminder Email Sent")
